mutation CreateUser {
  createUser {
    id
    name
  }
}

mutation UpdateUser($name: String!) {
  updateUser(name: $name) {
    id
    name
  }
}

mutation CreateRoom($name: String!) {
  createRoom(roomName: $name) {
    id
    name
  }
}

mutation SendMessage($input: CreateMessageInput!) {
  sendMessage(input: $input) {
    id
    content
    createdAt
    user {
      id
      name
      createdAt
    }
    repliedTo {
      id
      content
      createdAt
      user {
        id
        name
      }
    }
  }
}
