query Me {
  me {
    id
    name
    createdAt
  }
}

query Rooms {
  rooms {
    id
    name
    createdAt
  }
}

query Room($id: ID!, $before: String, $after: String, $first: Int, $last: Int) {
  room(roomId: $id) {
    id
    name
    createdAt
    messages(before: $before, after: $after, first: $first, last: $last) {
      pageInfo {
        hasPreviousPage
        hasNextPage
        startCursor
        endCursor
      }
      nodes {
        id
        content
        createdAt
        user {
          id
          name
          createdAt
        }
        repliedTo {
          id
          content
          createdAt
          user {
            id
            name
            createdAt
          }
        }
      }
    }
  }
}