subscription RoomMessages($id: ID!) {
  roomMessages(roomId: $id) {
    id
    content
    user {
      id
      name
    }
    repliedTo {
      id
      content
      user {
        id
        name
      }
    }
  }
}